title: Emerson Muniz
email: seuemail@example.com
description: "Bem-vindo ao meu site pessoal construído com Jekyll."
baseurl: "" # Leave empty
url: "<https://seu-usuario.github.io>" # Substitua com o URL do seu GitHub Pages
theme: minima
